# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: filter_conf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='filter_conf.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x66ilter_conf.proto\"\xc6\x01\n\nFilterConf\x12 \n\x11is_use_voxel_grid\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x0f\n\x02lx\x18\x02 \x01(\x01:\x03\x30.2\x12\x0f\n\x02ly\x18\x03 \x01(\x01:\x03\x30.2\x12\x0f\n\x02lz\x18\x04 \x01(\x01:\x03\x30.2\x12\x31\n\"is_use_statistical_outlier_removal\x18\x05 \x01(\x08:\x05\x66\x61lse\x12\x12\n\x06mean_k\x18\x06 \x01(\x01:\x02\x33\x30\x12\x1c\n\x0fstddevmulthresh\x18\x07 \x01(\x01:\x03\x30.6'
)




_FILTERCONF = _descriptor.Descriptor(
  name='FilterConf',
  full_name='FilterConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_use_voxel_grid', full_name='FilterConf.is_use_voxel_grid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lx', full_name='FilterConf.lx', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ly', full_name='FilterConf.ly', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lz', full_name='FilterConf.lz', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_use_statistical_outlier_removal', full_name='FilterConf.is_use_statistical_outlier_removal', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean_k', full_name='FilterConf.mean_k', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(30),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stddevmulthresh', full_name='FilterConf.stddevmulthresh', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(0.6),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=220,
)

DESCRIPTOR.message_types_by_name['FilterConf'] = _FILTERCONF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilterConf = _reflection.GeneratedProtocolMessageType('FilterConf', (_message.Message,), {
  'DESCRIPTOR' : _FILTERCONF,
  '__module__' : 'filter_conf_pb2'
  # @@protoc_insertion_point(class_scope:FilterConf)
  })
_sym_db.RegisterMessage(FilterConf)


# @@protoc_insertion_point(module_scope)
